# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 930ca028b225887c644a88f9afa141375cc4caa3c9716cccf8285f294f53f8870d928fd0836e8ea7d0ac701fb4f9dd78173219c2354fe6428cbf1b41f7ae4bd7

test:
  secret_key_base: ab0023d4f7a308207d561306ab63d5cb8a2f5a732532abd541e91e51f69a0c602237a3d62cecd84b5d40cfbcc6be0db77ef85f836f2a26018a7f8235d58a2e01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
